"""empty message

Revision ID: 118fad152f34
Revises: b77a6b316657
Create Date: 2016-07-08 13:40:43.119843

"""

# revision identifiers, used by Alembic.
revision = '118fad152f34'
down_revision = 'b77a6b316657'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('title', sa.Unicode(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('place')
    ### end Alembic commands ###
